In [2]:
import numpy as np

In [3]:
lst = ['Rajesh Adhikari']
arr = np.array(lst)
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['Rajesh Adhikari'], dtype='<U15')

In [4]:
lst2 = [
    [1, 2, 3],
    [4, 5, 6]
]

arr2 = np.array(lst2, dtype='float32')
arr2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [5]:
np.zeros(10, dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [6]:
np.ones([4, 5], dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0, 3, 2)

array([0, 2])

In [9]:
np.random.random((3,3 ))

array([[0.09855341, 0.05322484, 0.84962352],
       [0.79652271, 0.9270602 , 0.90274267],
       [0.7745861 , 0.33481799, 0.91791162]])

In [10]:
np.random.normal(0, 1, (3, 3))

array([[ 0.75567824,  0.83914919,  0.38184298],
       [ 1.33782579,  0.42284873, -0.15826585],
       [ 0.56860378,  0.83805477, -1.53976887]])

In [11]:
np.random.randint(0, 10, (3, 3))

array([[9, 7, 0],
       [6, 6, 6],
       [7, 0, 7]])

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.reshape(arr, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
arr.reshape((2, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [15]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.reshape(arr2, (2, 4))
np.reshape(arr2, (4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
arr1 = np.array([1, 1, 1, 1])
arr2 = np.array([2, 2, 2, 2])

concat_arr = np.concatenate((arr1, arr2))
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [18]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

b = np.array([
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

concat = np.concatenate((a, b))
concat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
concat_1 = np.concatenate((a, b), axis = 1)
concat_1

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [20]:
arr_1 = np.array([1, 2, 3, 4, 5, 6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [21]:
np.split(arr_1, 4)

ValueError: array split does not result in an equal division

In [22]:
np.array_split(arr_1, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [23]:
sp_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

sp_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [24]:
np.array_split(sp_2D, 4)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [25]:
np.split(sp_2D, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [26]:
np.array_split(sp_2D, 4, axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int32)]

In [29]:
import time

x1 = np.arange(1, 10000000)
x2 = np.arange(1, 10000000)

mul = np.zeros(x1.shape)
mul

array([0., 0., 0., ..., 0., 0., 0.])

In [30]:
start_time = time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]

end_time = time.process_time()

print(end_time - start_time)

C:\Users\USER\AppData\Local\Temp\ipykernel_17664\3143907123.py:4: RuntimeWarning: overflow encountered in scalar multiply
  mul[i] = x1[i]*x2[i]


34.53125


In [28]:
a = np.array([1, 2, 3])
b = 2
print(a+b)

[3 4 5]


In [32]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

print(f'shape of a: {a.shape}')
print(f'shape of b: {b.shape}')
print(a+b)

shape of a: (3,)
shape of b: (3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
