In [1]:
import numpy as np

In [11]:
lst = ['Rajesh Adhikari']
arr = np.array(lst)
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['Rajesh Adhikari'], dtype='<U15')

In [6]:
lst2 = [
    [1, 2, 3],
    [4, 5, 6]
]

arr2 = np.array(lst, dtype='float32')
arr2

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [9]:
np.zeros(10, dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [10]:
np.ones([4, 5], dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [4]:
np.arange(0, 3, 2)

array([0, 2])

In [5]:
np.random.random((3,3 ))

array([[0.29011717, 0.69582744, 0.36694647],
       [0.03855693, 0.53565432, 0.41595938],
       [0.68706859, 0.79690381, 0.39614711]])

In [6]:
np.random.normal(0, 1, (3, 3))

array([[ 0.0376108 ,  1.75707549, -1.60625967],
       [ 0.54221843,  0.37581152,  1.6560854 ],
       [-0.40097291,  1.15712765,  0.89481125]])

In [7]:
np.random.randint(0, 10, (3, 3))

array([[3, 9, 6],
       [4, 0, 6],
       [8, 8, 2]])

In [10]:
sm_arr = [
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
]

print(f"The dimension of sample array is: {sm_arr.dtype}")

AttributeError: 'list' object has no attribute 'dtype'