In [1]:
import numpy as np

In [2]:
lst = ['Rajesh Adhikari']
arr = np.array(lst)
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['Rajesh Adhikari'], dtype='<U15')

In [5]:
lst2 = [
    [1, 2, 3],
    [4, 5, 6]
]

arr2 = np.array(lst2, dtype='float32')
arr2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [6]:
np.zeros(10, dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [7]:
np.ones([4, 5], dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 3, 2)

array([0, 2])

In [10]:
np.random.random((3,3 ))

array([[0.90333945, 0.96565186, 0.88880355],
       [0.31744609, 0.81667441, 0.9821913 ],
       [0.50087528, 0.50915917, 0.61022272]])

In [11]:
np.random.normal(0, 1, (3, 3))

array([[ 0.41145299,  0.92302479,  0.27462433],
       [-0.71754056,  1.78477763,  1.85095342],
       [ 0.30823435, -0.84884381,  2.85102905]])

In [12]:
np.random.randint(0, 10, (3, 3))

array([[3, 3, 2],
       [4, 5, 5],
       [8, 3, 5]])

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
np.reshape(arr, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
arr.reshape((2, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [25]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.reshape(arr2, (2, 4))
np.reshape(arr2, (4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
arr1 = np.array([1, 1, 1, 1])
arr2 = np.array([2, 2, 2, 2])

concat_arr = np.concatenate((arr1, arr2))
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [31]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

b = np.array([
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

concat = np.concatenate((a, b))
concat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
concat_1 = np.concatenate((a, b), axis = 1)
concat_1

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [35]:
arr_1 = np.array([1, 2, 3, 4, 5, 6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [36]:
np.split(arr_1, 4)

ValueError: array split does not result in an equal division

In [37]:
np.array_split(arr_1, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [43]:
sp_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

sp_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [44]:
np.array_split(sp_2D, 4)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [45]:
np.split(sp_2D, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [46]:
np.array_split(sp_2D, 4, axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int32)]